### ISSUE TITLE
Restore #podcast

### ISSUE THREAD

**Issue by yuina1056** [mohikanz/mohikan-backup#46]
# Channel名
#podcast
# Feed URL

http://feed.mozaic.fm/
http://feeds.soundcloud.com/users/soundcloud:users:230945921/sounds.rss
http://feeds.rebuild.fm/rebuildfm
https://soussune.com/feed.xml
https://ajito.fm/index.xml
http://feeds.soundcloud.com/users/soundcloud:users:294673416/sounds.rss
https://yatteiki.fm/feed.xml

**Comment by peacock0803sz** [comment]
ref #49
