### ISSUE TITLE
Restore #news-it-ja

### ISSUE THREAD

**Issue by peacock0803sz** [mohikanz/mohikan-backup#6]
IT系ニュースサイト(日本語)

- gihyo.jp：総合
- クラウド Watch
- 窓の杜
- CNET Japan ブログネットワーク
- CodeZine:新着一覧
- ITmedia 総合記事一覧
- INTERNET Watch
- CNET Japan 最新情報　総合
- ZDNet Japan 最新情報　総合
- ギズモード・ジャパン
- Techable（テッカブル） -海外・国内のネットベンチャー系ニュースサイト

**Comment by swallowtail224** [comment]
リストの内容は追加

**Comment by peacock0803sz** [comment]
#18 mergeしたのでclose
